"""Initial migration with email and confirmation columns

Revision ID: 8619613b785d
Revises: 
Create Date: 2024-08-09 11:28:29.614873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8619613b785d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('is_confirmed', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('confirmed_on', sa.DateTime(), nullable=True))

        # Provide a unique constraint name
        batch_op.create_unique_constraint('uq_user_email', ['email'])
 
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')  # Drop the named constraint
        batch_op.drop_column('confirmed_on')
        batch_op.drop_column('is_confirmed')
        batch_op.drop_column('email')
    # ### end Alembic commands ###
