"""Add user_type column to User model

Revision ID: e1cd54cc9307
Revises: 8619613b785d
Create Date: 2024-08-21 00:09:41.212566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cd54cc9307'
down_revision = '8619613b785d'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=150), nullable=False, server_default='user'))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
